---
title: "Informationsbias und Selectionsbias"
subject: "Epidemiologie"
author: "Zehui Bai"
institute:   "Universität Bremen"    
date: "12.17.2019"
output: 
  beamer_presentation:  
    incremental: false  
    theme: "Madrid"  
    colortheme: "seahorse"  
    toc: true   
    slide_level: 2
    keep_tex: true
    fig_width: 5
    fig_height: 4
    fig_caption: true
    highlight: tango
  html_document:
    df_print: kable
fontsize: 10pt
header-includes: 
- \AtBeginSubsection{}   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error = FALSE, warning = FALSE)
library(knitr)
```



# Einführung


## Bias

### Definition
Eine Verzerrung kann als ein systematischer Fehler in einer epidemiologischen Studie definiert werden, der zu einer falschen Schätzung der tatsächlichen Auswirkung einer Exposition auf das interessierende Ergebnis führt



## Typen von Verzerrungen

Üblicherweise unterscheidet man drei Typen von Verzerrungen:

* den Selection Bias, d.h. die Verzerrung durch (nicht zufällige) Auswahl
* den Information Bias, d.h. die Verzerrung durch fehlerhafte Information bzw. Messung und
* den Confounding Bias, d.h. die Verzerrung durch mangelhafte Berücksichtigung von Störgrößen.






# Informationsbias

## Definition

### Informationsbias

Eine Verzerrung durch fehlerhafte Information entsteht.

* Ein Fehler bei der Messung von Expositions-, Kovariablen- oder Ergebnisvariablen, der zu einer unterschiedlichen Qualität der Informationen zwischen den Vergleichsgruppen führt




## Bemerkungen

* Information bias ist die Folge eines Fehlers im Design oder Durchführung der Studie
* Ist unabhängig von der Studienteilnahme aber abhängig vom Verfahren der Informationsbeschaffung
* Besonders anfällig für einen Information Bias sind Variablen, die retrospektiv erfasst werden. 




# Typen von Informationsbias

## Interviewer Bias

###

Wenn Interviewer eine gewisse Erwartungshaltung hinsichtlich des Expositionseffektes hat, könnten Fälle und Kontrollen im Interview bewusst oder unbewusst unterschiedlich befragt werden.


## Typischer Interviewer Bias

Ist z.B. der Interviewer von einem schädlichen Einfluss des Studienfaktors überzeugt, wird intensiver bei Fallgruppen (z.B. durch gezieltes Nachfragen) nach der Exposition geforscht  

Konsequenz: 

* mehr Exposition bei Fallgruppen als dies in Wirklichkeit
* führt zur Überschätzung des Odds Ratios 




## Maßnahmen gegen Interviewer Bias

* Einem Interviewer Bias kann dadurch entgegengesteuert werden, dass dem Interviewer **der Fall- bzw. Kontrollstatus einer Person nicht mitgeteilt** wird. (Klinische Studien:Verblindung).
    + Allerdings kann dies in epidemiologischen Beobachtungsstudien nur in Ausnahmefällen durchgeführt werden. 
* Der Verwendung **standardisierter Fragebögen** und der intensiven **Schulung** sowie dem **Monitoring des Interviewerpersonals** kommen deshalb hier große Bedeutung zu.






## Recall Bias

###

Wird die Exposition durch Selbstangabe der betroffenen Person selbst oder ihrer Angehörigen rückblickend ermittelt, so kann es zu einem Recall Bias, d.h. zu einer Verzerrung durch eine **unterschiedliche Erinnerungsfähigkeit** bei Fällen und Kontrollen kommen.


## Beispiel

In Fall-Kontroll-Studien bei schweren Krankheiten:

* In der Fallgruppe hat bei Erkrankten schon vor der Studienteilnahme ein intensives Nachdenken über die möglichen Ursachen der Krankheit eingesetzt.
* Dies ist in der Regel nicht der Fall in der Kontrollgruppe, die nicht von einer bedrohlichen Krankheit betroffen ist.
* Unterschied $\rightarrow$ eine Überschätzung des entsprechenden Effektes





## Maßnahme gegen Recall Bias

Durch **stark strukturierte Fragebögen** und **objektive Messungen**, sofern sie zuverlässig auf zurückliegende Expositionen schließen lassen.

die Auswirkungen dieser selektiven Erinnerung zu verringern.









# Selectionsbias


## Definition

### Auswahlverzerrung

werden bei der Auswahl aus der Zielpopulation in die Studienpopulation entstehen.




## Beispiel: 







# Typen von Selectionsbias

## Non-Response Bias

Die Verzerrung durch systematische Nicht-Teilnahme an der Studie.




## Beispiel in Querschnittsstudien

Bei umweltepidemiologischen Untersuchungen zur Frage von Zusammenhängen zwischen Luftverschmutzung und Atemwegserkrankungen:

* Höhere Interesse zur Studienteilnahme besteht, wenn man erkrankt ist oder wenn man in einer besonders belasteten Region wohnt. 
* Personen, die weder erkrankt sind noch in einem exponierten Gebiet wohnen, haben meist ein geringeres Interesse.




## Maßnahmen gegen Non-Response Bias

Für Nichtteilnahme:

**Mehr Personen auszuwählen**, als für die Studie benötigt werden, um die erforderliche Größe der Studienpopulation zu erreichen.







## Migration Bias

Die Verzerrung durch systematische Wanderungsbewegungen.

Als häufigste Form eines Migration Bias gilt dann die Wanderung Kranker von einem exponierten in einen nicht exponierten Status. 





## Beispiel

In der Arbeitswelt tritt im Verlaufe der Arbeitstätigkeit eine Erkrankung auf, die dem Arbeitsplatz ursächlich zugeordnet wird, so werden Arbeiter nach Eintritt der Erkrankung häufig auf nicht exponierte Arbeitsplätze versetzt. 

* $\rightarrow$ eine Unterschätzung des Odds Ratios zur Folge
* In nicht exponierten Regionen überproportional viele Kranke anzutreffen sind.






## Literaturverzeichnis

* Ahrens,W. Vorlesung Epidemiologie, Störgrößen und Verzerrungen
* Kreienbrock, Lothar, Pigeot, Iris, Ahrens, Wolfgang, Epidemiologische Methoden,4.4 Systematische Fehler (Bias)
* Hammer, Gaël P.; Prel, Jean-Baptist du; Blettner, Maria. Vermeidung verzerrter Ergebnisse in Beobachtungsstudien













